import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import ContextProvider from '@/context/ContextProvider';
const HeaderDynamic = dynamic(() => import('@/layout/Header'), {
  ssr: false,
});
import GlobalsLayout from '@/components/GlobalsLayout';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'react-toastify/dist/ReactToastify.css';
import Footer from '@/layout/Footer';
import dynamic from 'next/dynamic';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NET Movie',
  metadataBase: new URL('http://localhost:3000'),
  description: 'Generated by create next app',
  icons: {
    icon: ['/favicon/favicon.ico?v=4'],
    apple: ['/favicon/apple-touch-icon.png?v=4'],
    shortcut: ['/favicon/apple-touch-icon.png'],
  },
  manifest: '/favicon/site.webmanifest',
  openGraph: {
    title: 'Acme',
    description: 'Acme is a...',
    images: 'images/logo.jpg',
  },
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en-US',
      'de-DE': '/de-DE',
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ContextProvider>
          <GlobalsLayout>
            <HeaderDynamic />
            {children}
            <Footer />
          </GlobalsLayout>
        </ContextProvider>
      </body>
    </html>
  );
}
