import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import ContextProvider from '@/context/ContextProvider';
import Header from '@/layout/Header';
import GlobalsLayout from '@/components/GlobalsLayout';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'react-toastify/dist/ReactToastify.css';
import Footer from '@/layout/Footer';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'NET Movie',
  description: 'Generated by create next app',
  icons: {
    icon: ['/favicon/favicon.ico?v=4'],
    apple: ['/favicon/apple-touch-icon.png?v=4'],
    shortcut: ['/favicon/apple-touch-icon.png'],
  },
  manifest: '/favicon/site.webmanifest',
  openGraph: {
    title: 'Acme',
    description: 'Acme is a...',
    images: 'images/logo.jpg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ContextProvider>
          <GlobalsLayout>
            <Header />
            {children}
            <Footer />
          </GlobalsLayout>
        </ContextProvider>
      </body>
    </html>
  );
}
